- name: Check for coverage-diff.html
  stat:
    path: "{{ ansible_user_dir }}/zuul-output/logs/coverage-diff.html"
    get_checksum: false
    get_mime: false
    get_md5: false
  register: coverage_diff_html_stat

- name: Register current coverage report as an artifact
  when: coverage_diff_html_stat.stat.exists
  zuul_return:
    data:
      zuul:
        artifacts:
          - name: "Full coverage report (current)"
            url: "coverage-current.html"

- name: Register previous coverage report as an artifact
  when: coverage_diff_html_stat.stat.exists
  zuul_return:
    data:
      zuul:
        artifacts:
          - name: "Full coverage report (previous)"
            url: "coverage-previous.html"

- name: Register coverage report diff as an artifact
  when: coverage_diff_html_stat.stat.exists
  zuul_return:
    data:
      zuul:
        artifacts:
          - name: "Coverage report: difference in coverage"
            url: "coverage-diff.html"
