- name: Place for previous version of sources
  file:
    path: "{{ (previous_source_prefix + '/' + zuul.project.canonical_hostname + '/' + zuul.project.name) | dirname }}"
    state: directory

- name: Prepare copy of the previous version of sources
  shell:
    cmd: git worktree add {{ previous_source_prefix }}/{{ zuul.project.canonical_hostname }}/{{ zuul.project.name }} origin/$(git rev-parse --abbrev-ref HEAD)
    chdir: "{{ zuul.project.src_dir }}"
